### PR TITLE
Added scrapper for MangaSupa.com

### PR DESCRIPTION
**Pull request by kozec**
Hello,

I needed this scrapper for myself, but it may be useful in general. There is no big magic here, as site is very simple.

### CODE REVIEW

**Comment by Hamuko** [comment]
Doesn't seem to have any tests.

**Comment by kozec** [comment]
> Doesn't seem to have any tests.

Should it have?

**Comment by Hamuko** [comment]
>Should it have?
Yes. [Read this](https://github.com/Hamuko/cum/blob/master/CONTRIBUTING.md).

**Comment by kozec** [comment]
Ok, tests added.

I'd suggest mentioning them at https://github.com/Hamuko/cum/wiki/Implementing-scrapers , probably along with explanation for method(?) `def from_url(url)`.

**Comment by Hamuko** [comment]
Merged. I rebased your commit on top of the master branch since there was so much happening there and this was isolated enough not to require a merge commit. There was also a handful of style errors which I corrected before merging to master.

To be completely honest, I don't really give a shit about this scraper. It's not really confidence inducing to see a site that doesn't work on HTTPS due to mixed content from its own domain. But hey, as long as someone else is willing to maintain the scraper, I don't have an objection for including it. Since there are tests here now, I'll be relying on that to verify that the scraper still works and all the tests passed for me.

**Pull request closed without merging**
